version: '3.8'

volumes: 
  users_db_data: 
    driver: local
networks:
  users-network: {}

services:
  users-db:
      image: mysql:latest
      container_name: users-db
      restart: always
      environment:
      - MYSQL_HOSTNAME:${MYSQL_HOSTNAME}
      - MYSQL_DATABASE:${MYSQL_DATABASE}
      - MYSQL_USER:${MYSQL_USER}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
      ports:
        - "3306:3306"
      volumes:
        - users_db_data:/var/lib/mysql
      networks:
        - users-network
  users_service:
    container_name: users-service
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - MYSQL_HOSTNAME=users-db
      - MYSQL_DATABASE=zeroer
      - MYSQL_USER=zeroer
      - MYSQL_PASSWORD=secret
      - MYSQL_PORT=3306
    ports: 
      - "5000:5000"
    depends_on: 
      - users-db
    networks:
      - users-network

